# Generated by Django 3.2.9 on 2021-11-05 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Navigations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentnav',
            name='isparent',
        ),
        migrations.AddField(
            model_name='submenu',
            name='parentNav',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Navigations.parentnav'),
            preserve_default=False,
        ),
    ]
