# Generated by Django 3.2.9 on 2021-11-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Navigations', '0002_auto_20211106_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentnav',
            name='hasChild',
            field=models.BooleanField(default=False),
        ),
    ]
