# Generated by Django 3.2.9 on 2021-11-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Navigations', '0003_parentnav_haschild'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentnav',
            name='slug',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
