# Generated by Django 3.2.9 on 2021-11-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('paragraph', models.CharField(blank=True, max_length=1000)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
