# Generated by Django 3.2.9 on 2021-11-18 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choose',
        ),
    ]
